
const productList = [
    {
        product_id: "CFM0001",
        product_title: "Café Cojute 400gr",
        product_description: "Café tostado y molido, 100% salvadoreño de las fincas de Cojutepeque. Presentación de 400gr en empaque dorado.",
        product_price: 3.90,
        product_offer_price: 3.50,
        cooperative: "Sociedad Cooperativa de Cafetaleros de Cuscatlán de R.L.",
        form: "Molido",
        brand: "Cojute",
        certifications: false,
        initial: 20,
        sold: 4,
        stock: 16,
        department: "Cuscatlán",
        municipality: "Cojutepeque",
        zone: "Central",
        weight: 400,
        height: "700-900",
        descriptive_height: "Media",
        type: "Cuzcatleco y Catisic",
        mix: "Achocolatado, frutales y forestales",
        toasted_level: "Medio",
        process: "Molido",
        acidity: "Suave",
        image_url: "/assets/Images/Cojulte v2.JPG",
        cart_product_quantity: 1
    },

    {
        product_id: "CFM0002",
        product_title: "Café San Carlos Dos 454gr (Dorado)",
        product_description: "Café tostado y molido, 100% salvadoreño de las fincas de Morazán. Presentación de 454gr en empaque dorado.",
        product_price: 6.95,
        product_offer_price: 6.25,
        cooperative: "Cooperativa San Carlos Dos de R.L.",
        form: "Molido",
        brand: "San Carlos 2",
        certifications: true,
        initial: 30,
        sold: 10,
        stock: 20,
        department: "Osicala",
        municipality: "Morazán",
        zone: "Oriente",
        weight: 454,
        height: "900-1300",
        descriptive_height: "Media",
        type: "Bourbon",
        mix: "Achocolatado, cuerpo delicado",
        toasted_level: "Medio",
        process: "Molido",
        acidity: "Suave",
        image_url: "/assets/Images/San Carlos Dos Dorado v2.JPG",
        cart_product_quantity: 1
    },

    {
        product_id: "CFM0003",
        product_title: "Café San Carlos Dos 454gr (Premium)",
        product_description: "Café tostado y molido, 100% salvadoreño de las fincas de Morazán. Presentación Premium de 454gr en empaque celeste.",
        product_price: 9.90,
        product_offer_price: 8.90,
        cooperative: "Cooperativa San Carlos Dos de R.L.",
        form: "Molido",
        brand: "San Carlos 2",
        certifications: true,
        initial: 10,
        sold: 4,
        stock: 6,
        department: "Osicala",
        municipality: "Morazán",
        zone: "Oriente",
        weight: 454,
        height: "1300-1663",
        descriptive_height: "Estricta altura",
        type: "Bourbon",
        mix: "Achocolatado, jugo de caña de azúcar",
        toasted_level: "Medio",
        process: "Molido",
        acidity: "Citrico Toronja",
        image_url: "/assets/Images/San Carlos Dos v2.JPG",
        cart_product_quantity: 1
    },
    {
        product_id: "CFM0004",
        product_title: "Café Cuzca Plus 400gr",
        product_description: "Café tostado y molido, 100% salvadoreño de las fincas de Chalchuapa, Santa Ana. Presentación de 400gr.",
        product_price: 5.95,
        product_offer_price: 5.35,
        cooperative: "Cooperativa Cuzcachapa de R.L.",
        form: "Molido",
        brand: "Chalchuapa",
        certifications: true,
        initial: 10,
        sold: 10,
        stock: 0,
        department: "Santa Ana",
        municipality: "Chalchuapa",
        zone: "Occidente",
        weight: 400,
        height: "1200-1400",
        descriptive_height: "Alta",
        type: "Notas vinosas y frutales",
        mix: "Achocolatado, jugo de caña de azúcar",
        toasted_level: "Medio Oscuro",
        process: "Molido",
        acidity: "Suave",
        image_url: "/assets/Images/Cuzca Plus v2.JPG",
        cart_product_quantity: 1
    },
    {
        product_id: "CFM0005",
        product_title: "Café Cuzcachapa 400gr",
        product_description: "Café tostado y molido, 100% salvadoreño de las fincas de Chalchuapa, Santa Ana. Presentación de 400gr.",
        product_price: 4.95,
        product_offer_price: 4.45,
        cooperative: "Cooperativa Cuzcachapa de R.L.",
        form: "Molido",
        brand: "Chalchuapa",
        certifications: true,
        initial: 40,
        sold: 1,
        stock: 39,
        department: "Santa Ana",
        municipality: "Chalchuapa",
        zone: "Occidente",
        weight: 400,
        height: "900-1200",
        descriptive_height: "Media",
        type: "Blend de café de altura (Cuzcatleco, Catisic, Pacas, Tekisic, entre otros)",
        mix: "Mucho cuerpo y notas achocolatadas",
        toasted_level: "Medio",
        process: "Molido",
        acidity: "Baja",
        image_url: "/assets/Images/Cuzcachapa v2.JPG",
        cart_product_quantity: 1
    }

]

export { productList }